run:
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
